name: build binaries
on:
  push:
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ["3.11"]
    steps:
      # Check-out repository
      - uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
       #Build python script into a single execute
      - name: Package Application with PyInstaller
        run: |
          pyinstaller -n wokie -F main.py
      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WOKIE_binary_${{ matrix.operating-system }}
          path:  dist