name: Tests

on:
  push:
    # branches: [ dependency-updates ]
  #   branches: [ master, main, development]
    branches-ignore:
      - master
      - main
      - development
  pull_request:
    branches: [ master, main, development]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest, ubuntu-latest, macOS-latest]
        python-version: ["3.11.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run tests
        run: |
          pytest

